# Generated by Django 5.0.6 on 2026-08-01

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_public_site_configuration(apps, schema_editor):
    SiteConfiguration = apps.get_model("core", "SiteConfiguration")
    SeoConfiguration = apps.get_model("core", "SeoConfiguration")
    HomePageConfiguration = apps.get_model("core", "HomePageConfiguration")
    HeaderNavigationItem = apps.get_model("core", "HeaderNavigationItem")
    FooterSection = apps.get_model("core", "FooterSection")
    FooterLink = apps.get_model("core", "FooterLink")
    HomeFeatureCard = apps.get_model("core", "HomeFeatureCard")
    StaticPage = apps.get_model("core", "StaticPage")

    site_configuration, _ = SiteConfiguration.objects.get_or_create(
        singleton_key=1,
        defaults={
            "site_name": "برند شما",
            "tagline": "واردات و رهگیری شفاف خودرو",
            "primary_color": "#2563EB",
            "accent_color": "#38BDF8",
            "surface_color": "#17191D",
        },
    )

    SeoConfiguration.objects.get_or_create(
        site_configuration=site_configuration,
        defaults={
            "default_meta_description": "مشاهدهٔ خودروهای موجود، ثبت درخواست خودروی سفارشی و رهگیری شفاف فرایند ارسال خودرو.",
            "default_meta_keywords": "واردات خودرو, خودرو از عمان, رهگیری خودرو, درخواست خودرو",
        },
    )
    home_page, _ = HomePageConfiguration.objects.get_or_create(
        site_configuration=site_configuration,
        defaults={
            "hero_eyebrow": "واردات خودرو از عمان",
            "hero_title": "خودرو را انتخاب کنید؛ مسیر تحویل را شفاف ببینید.",
            "hero_description": "خودروهای موجود را بررسی کنید، برای خرید با مشاور ارتباط بگیرید و پس از فروش، وضعیت ارسال را با کد اختصاصی دنبال کنید.",
            "primary_cta_label": "خودروهای موجود",
            "primary_cta_destination": "/cars/",
            "secondary_cta_label": "درخواست خودرو",
            "secondary_cta_destination": "/requests/vehicle/",
            "featured_vehicles_heading": "خودروهای موجود",
            "route_title": "مسیر واردات",
            "route_origin_label": "عمان",
            "route_destination_label": "ایران",
            "route_transport_label": "حمل دریایی و زمینی",
            "route_duration_label": "بر اساس مرحلهٔ فعلی خودرو",
            "tracking_section_heading": "وضعیت خودرو را مرحله‌به‌مرحله ببینید",
            "tracking_section_description": "پس از نهایی‌شدن فروش، یک کد رهگیری یکتا دریافت می‌کنید تا تاریخچه و زمان تقریبی باقی‌مانده را مشاهده کنید.",
        },
    )

    for sort_order, label, destination in [
        (10, "صفحهٔ اصلی", "/"),
        (20, "خودروهای موجود", "/cars/"),
        (30, "مسیر واردات", "/#import-route"),
        (40, "رهگیری خودرو", "/track/"),
        (50, "خدمات", "/services/"),
        (60, "درباره ما", "/about/"),
        (70, "تماس با ما", "/contact/"),
    ]:
        HeaderNavigationItem.objects.get_or_create(
            label=label,
            destination=destination,
            defaults={"sort_order": sort_order, "is_enabled": True},
        )

    quick_links, _ = FooterSection.objects.get_or_create(
        title="دسترسی سریع",
        defaults={"sort_order": 10, "is_enabled": True},
    )
    service_links, _ = FooterSection.objects.get_or_create(
        title="خدمات",
        defaults={"sort_order": 20, "is_enabled": True},
    )
    for section, sort_order, label, destination in [
        (quick_links, 10, "صفحهٔ اصلی", "/"),
        (quick_links, 20, "خودروهای موجود", "/cars/"),
        (quick_links, 30, "رهگیری خودرو", "/track/"),
        (service_links, 10, "درخواست خودروی سفارشی", "/requests/vehicle/"),
        (service_links, 20, "خدمات", "/services/"),
        (service_links, 30, "مجله", "/blog/"),
    ]:
        FooterLink.objects.get_or_create(
            section=section,
            label=label,
            defaults={
                "destination": destination,
                "sort_order": sort_order,
                "is_enabled": True,
            },
        )

    for icon, sort_order, title, description, cta_label, cta_destination in [
        (
            "car",
            10,
            "خودروهای موجود",
            "خودروهای آمادهٔ فروش را ببینید و برای مذاکره با مشاوران ارتباط بگیرید.",
            "مشاهدهٔ خودروها",
            "/cars/",
        ),
        (
            "track",
            20,
            "رهگیری شفاف",
            "پس از فروش، مسیر و مراحل تحویل خودرو را با کد اختصاصی دنبال کنید.",
            "رهگیری خودرو",
            "/track/",
        ),
        (
            "message",
            30,
            "خودروی سفارشی",
            "اگر خودرو در موجودی نیست، مشخصات دلخواه خود را برای بررسی بازار ثبت کنید.",
            "ثبت درخواست",
            "/requests/vehicle/",
        ),
    ]:
        HomeFeatureCard.objects.get_or_create(
            home_page=home_page,
            title=title,
            defaults={
                "icon": icon,
                "description": description,
                "cta_label": cta_label,
                "cta_destination": cta_destination,
                "sort_order": sort_order,
                "is_enabled": True,
            },
        )

    for slug, title, intro, body, keywords in [
        (
            "services",
            "خدمات ما",
            "از انتخاب خودرو تا رهگیری مراحل تحویل، اطلاعات لازم را در یک مسیر شفاف در اختیار شما قرار می‌دهیم.",
            "خودروهای موجود را بررسی کنید یا مشخصات خودروی موردنظر خود را ثبت کنید تا کارشناسان بازار آن را بررسی کنند. پس از نهایی‌شدن فروش، رهگیری مراحل تحویل با کد اختصاصی در دسترس خواهد بود.",
            "خدمات واردات خودرو, رهگیری خودرو",
        ),
        (
            "about",
            "دربارهٔ ما",
            "این صفحه برای معرفی مجموعه، رویکرد کاری و اطلاعات موردنیاز مشتریان از پنل مدیریت قابل‌ویرایش است.",
            "محتوای این بخش را مدیر سایت از پنل مدیریت تکمیل و به‌روزرسانی می‌کند.",
            "درباره شرکت واردات خودرو",
        ),
        (
            "contact",
            "تماس با ما",
            "راه‌های ارتباطی مجموعه از تنظیمات اصلی سایت مدیریت می‌شوند.",
            "شماره تلفن، ایمیل، آدرس و لینک تلگرام را مدیر سایت در بخش تنظیمات اصلی وارد می‌کند.",
            "تماس با مشاور خودرو",
        ),
    ]:
        StaticPage.objects.get_or_create(
            slug=slug,
            defaults={
                "title": title,
                "intro": intro,
                "body": body,
                "meta_description": intro,
                "meta_keywords": keywords,
                "is_published": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_alter_carphoto_options_car_seo_description_and_more"),
        ("core", "0002_delete_orderrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "ستون فوتر",
                "verbose_name_plural": "ستون‌های فوتر",
                "ordering": ["sort_order", "pk"],
                "permissions": [("manage_site_footer", "Can manage public site footer")],
            },
        ),
        migrations.CreateModel(
            name="HeaderNavigationItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=80)),
                ("destination", models.CharField(max_length=500, validators=[core.models.validate_public_destination])),
                ("aria_label", models.CharField(blank=True, max_length=160)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("open_in_new_tab", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "آیتم منوی هدر",
                "verbose_name_plural": "آیتم‌های منوی هدر",
                "ordering": ["sort_order", "pk"],
                "permissions": [("manage_site_navigation", "Can manage public site navigation")],
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("site_name", models.CharField(default="برند شما", max_length=120)),
                ("legal_name", models.CharField(blank=True, max_length=180)),
                ("tagline", models.CharField(blank=True, max_length=220)),
                ("logo_light", models.FileField(blank=True, null=True, upload_to="site/identity/", validators=[django.core.validators.FileExtensionValidator(["png", "jpg", "jpeg", "webp", "svg"])])),
                ("logo_dark", models.FileField(blank=True, null=True, upload_to="site/identity/", validators=[django.core.validators.FileExtensionValidator(["png", "jpg", "jpeg", "webp", "svg"])])),
                ("favicon", models.FileField(blank=True, null=True, upload_to="site/identity/", validators=[django.core.validators.FileExtensionValidator(["png", "ico"])])),
                ("primary_color", models.CharField(default="#2563EB", max_length=7, validators=[django.core.validators.RegexValidator(message="رنگ باید به‌صورت کد شش‌رقمی HEX، مانند #2563EB، وارد شود.", regex="^#[0-9A-Fa-f]{6}$")])),
                ("accent_color", models.CharField(default="#38BDF8", max_length=7, validators=[django.core.validators.RegexValidator(message="رنگ باید به‌صورت کد شش‌رقمی HEX، مانند #2563EB، وارد شود.", regex="^#[0-9A-Fa-f]{6}$")])),
                ("surface_color", models.CharField(default="#17191D", max_length=7, validators=[django.core.validators.RegexValidator(message="رنگ باید به‌صورت کد شش‌رقمی HEX، مانند #2563EB، وارد شود.", regex="^#[0-9A-Fa-f]{6}$")])),
                ("support_phone", models.CharField(blank=True, max_length=40)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("telegram_url", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("copyright_text", models.CharField(blank=True, max_length=220)),
            ],
            options={
                "verbose_name": "تنظیمات اصلی سایت",
                "verbose_name_plural": "تنظیمات اصلی سایت",
                "permissions": [
                    ("manage_site_identity", "Can manage site identity and brand assets"),
                    ("manage_site_seo", "Can manage global site SEO"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("platform", models.CharField(choices=[("telegram", "Telegram"), ("instagram", "Instagram"), ("whatsapp", "WhatsApp"), ("youtube", "YouTube"), ("linkedin", "LinkedIn"), ("other", "Other")], max_length=30)),
                ("label", models.CharField(blank=True, max_length=80)),
                ("url", models.URLField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "لینک شبکهٔ اجتماعی",
                "verbose_name_plural": "لینک‌های شبکه‌های اجتماعی",
                "ordering": ["sort_order", "pk"],
                "permissions": [("manage_site_social_links", "Can manage public social links")],
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(allow_unicode=True, max_length=80, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("intro", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("meta_title", models.CharField(blank=True, max_length=160)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("is_published", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "صفحهٔ عمومی",
                "verbose_name_plural": "صفحات عمومی",
                "ordering": ["title"],
                "permissions": [("manage_static_pages", "Can manage public static pages")],
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=500, validators=[core.models.validate_public_destination])),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("section", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="links", to="core.footersection")),
            ],
            options={
                "verbose_name": "لینک فوتر",
                "verbose_name_plural": "لینک‌های فوتر",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="HomePageConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hero_eyebrow", models.CharField(blank=True, max_length=120)),
                ("hero_title", models.CharField(blank=True, max_length=220)),
                ("hero_description", models.TextField(blank=True)),
                ("hero_background_image", models.ImageField(blank=True, null=True, upload_to="site/home/", validators=[django.core.validators.FileExtensionValidator(["png", "jpg", "jpeg", "webp"])])),
                ("hero_mobile_background_image", models.ImageField(blank=True, null=True, upload_to="site/home/", validators=[django.core.validators.FileExtensionValidator(["png", "jpg", "jpeg", "webp"])])),
                ("hero_image_alt", models.CharField(blank=True, max_length=180)),
                ("primary_cta_label", models.CharField(blank=True, max_length=80)),
                ("primary_cta_destination", models.CharField(blank=True, max_length=500, validators=[core.models.validate_public_destination])),
                ("secondary_cta_label", models.CharField(blank=True, max_length=80)),
                ("secondary_cta_destination", models.CharField(blank=True, max_length=500, validators=[core.models.validate_public_destination])),
                ("featured_vehicles_heading", models.CharField(blank=True, max_length=140)),
                ("route_title", models.CharField(blank=True, max_length=140)),
                ("route_origin_label", models.CharField(blank=True, max_length=80)),
                ("route_destination_label", models.CharField(blank=True, max_length=80)),
                ("route_transport_label", models.CharField(blank=True, max_length=120)),
                ("route_duration_label", models.CharField(blank=True, max_length=120)),
                ("route_panel_image", models.ImageField(blank=True, null=True, upload_to="site/home/", validators=[django.core.validators.FileExtensionValidator(["png", "jpg", "jpeg", "webp"])])),
                ("tracking_section_heading", models.CharField(blank=True, max_length=140)),
                ("tracking_section_description", models.TextField(blank=True)),
                ("hero_featured_car", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="hero_features", to="cars.car")),
                ("site_configuration", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="home_page", to="core.siteconfiguration")),
            ],
            options={
                "verbose_name": "محتوای صفحهٔ اول",
                "verbose_name_plural": "محتوای صفحهٔ اول",
                "permissions": [("manage_site_content", "Can manage public homepage content")],
            },
        ),
        migrations.CreateModel(
            name="HomeFeatureCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("icon", models.CharField(choices=[("car", "خودرو"), ("track", "رهگیری"), ("message", "پیام"), ("shield", "اطمینان")], default="car", max_length=20)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("cta_label", models.CharField(blank=True, max_length=80)),
                ("cta_destination", models.CharField(blank=True, max_length=500, validators=[core.models.validate_public_destination])),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("home_page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feature_cards", to="core.homepageconfiguration")),
            ],
            options={
                "verbose_name": "کارت صفحهٔ اول",
                "verbose_name_plural": "کارت‌های صفحهٔ اول",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SeoConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("default_meta_title", models.CharField(blank=True, max_length=160)),
                ("default_meta_description", models.CharField(blank=True, max_length=320)),
                ("default_meta_keywords", models.CharField(blank=True, max_length=500)),
                ("default_robots", models.CharField(default="index, follow", max_length=80)),
                ("google_site_verification", models.CharField(blank=True, max_length=255)),
                ("bing_site_verification", models.CharField(blank=True, max_length=255)),
                ("twitter_handle", models.CharField(blank=True, max_length=80)),
                ("default_og_image", models.ImageField(blank=True, null=True, upload_to="site/seo/", validators=[django.core.validators.FileExtensionValidator(["png", "jpg", "jpeg", "webp"])])),
                ("site_configuration", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="seo", to="core.siteconfiguration")),
            ],
            options={
                "verbose_name": "تنظیمات سئوی سایت",
                "verbose_name_plural": "تنظیمات سئوی سایت",
            },
        ),
        migrations.RunPython(seed_public_site_configuration, migrations.RunPython.noop),
    ]
