# Generated by Django 5.0.6 on 2026-08-02

import django.db.models.deletion
from django.db import migrations, models

import core.models


def seed_home_quick_actions(apps, schema_editor):
    HomePageConfiguration = apps.get_model("core", "HomePageConfiguration")
    HomeQuickAction = apps.get_model("core", "HomeQuickAction")

    defaults = [
        (
            "inventory",
            "خودروهای موجود",
            "/cars/",
            "مشاهدهٔ خودروهای موجود برای فروش",
            10,
        ),
        (
            "route",
            "مسیر واردات",
            "/#import-route",
            "مشاهدهٔ مسیر واردات خودرو",
            20,
        ),
        (
            "tracking",
            "رهگیری خودرو",
            "/track/",
            "رهگیری وضعیت خودروی خریداری‌شده",
            30,
        ),
        (
            "request",
            "درخواست خودرو",
            "/requests/vehicle/",
            "ثبت درخواست خودروی سفارشی",
            40,
        ),
        (
            "support",
            "ارتباط با مشاور",
            "/contact/",
            "مشاهدهٔ راه‌های ارتباط با مشاور",
            50,
        ),
    ]

    for home_page in HomePageConfiguration.objects.all().iterator():
        for action, label, destination, aria_label, sort_order in defaults:
            HomeQuickAction.objects.get_or_create(
                home_page_id=home_page.pk,
                action=action,
                defaults={
                    "label": label,
                    "destination": destination,
                    "aria_label": aria_label,
                    "sort_order": sort_order,
                    "is_enabled": True,
                    "open_in_new_tab": False,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_footersection_headernavigationitem_siteconfiguration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeQuickAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("inventory", "خودروهای موجود"),
                            ("route", "مسیر واردات"),
                            ("tracking", "رهگیری خودرو"),
                            ("request", "درخواست خودرو"),
                            ("support", "ارتباط با مشاور"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                (
                    "destination",
                    models.CharField(
                        max_length=500,
                        validators=[core.models.validate_public_destination],
                    ),
                ),
                ("aria_label", models.CharField(blank=True, max_length=160)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                (
                    "home_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_actions",
                        to="core.homepageconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسترسی سریع صفحهٔ اول",
                "verbose_name_plural": "دسترسی‌های سریع صفحهٔ اول",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="homequickaction",
            constraint=models.UniqueConstraint(
                fields=("home_page", "action"),
                name="core_unique_home_quick_action_type",
            ),
        ),
        migrations.RunPython(seed_home_quick_actions, migrations.RunPython.noop),
    ]
