# Generated by Django 5.0.6 on 2026-08-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_blog_header_navigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=40, verbose_name='شمارهٔ تلفن')),
                ('subject', models.CharField(blank=True, max_length=180, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('read', 'خوانده\u200cشده'), ('closed', 'بسته\u200cشده')], default='new', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
