# Generated by Django 5.0.6 on 2026-08-13 09:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogconfiguration_post_seo_and_more'),
        ('core', '0005_add_blog_header_navigation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogconfiguration',
            options={'verbose_name': 'ØªÙ†Ø¸ÛŒÙ…Ø§Øª ÙˆØ¨Ù„Ø§Ú¯', 'verbose_name_plural': 'ØªÙ†Ø¸ÛŒÙ…Ø§Øª ÙˆØ¨Ù„Ø§Ú¯'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Ø¯Ø³ØªÙ‡â€ŒØ¨Ù†Ø¯ÛŒ ÙˆØ¨Ù„Ø§Ú¯', 'verbose_name_plural': 'Ø¯Ø³ØªÙ‡â€ŒØ¨Ù†Ø¯ÛŒâ€ŒÙ‡Ø§ÛŒ ÙˆØ¨Ù„Ø§Ú¯'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at', '-created_at'], 'permissions': [('publish_post', 'Can publish and unpublish blog posts')], 'verbose_name': 'Ù…Ø·Ù„Ø¨ ÙˆØ¨Ù„Ø§Ú¯', 'verbose_name_plural': 'Ù…Ø·Ø§Ù„Ø¨ ÙˆØ¨Ù„Ø§Ú¯'},
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='articles_per_page',
            field=models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(48)], verbose_name='ØªØ¹Ø¯Ø§Ø¯ Ù…Ø·Ù„Ø¨ Ø¯Ø± Ù‡Ø± ØµÙ\x81Ø\xadÙ‡'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='default_meta_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='ØªÙˆØ¶ÛŒØ\xad Ù¾ÛŒØ´â€ŒÙ\x81Ø±Ø¶ Ø³Ø¦ÙˆÛŒ ÙˆØ¨Ù„Ø§Ú¯'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='default_meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ú©Ù„ÛŒØ¯ÙˆØ§Ú˜Ù‡â€ŒÙ‡Ø§ÛŒ Ù¾ÛŒØ´â€ŒÙ\x81Ø±Ø¶ ÙˆØ¨Ù„Ø§Ú¯'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='default_meta_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Ø¹Ù†ÙˆØ§Ù† Ù¾ÛŒØ´â€ŒÙ\x81Ø±Ø¶ Ø³Ø¦ÙˆÛŒ ÙˆØ¨Ù„Ø§Ú¯'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='default_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/seo/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='ØªØµÙˆÛŒØ± Ù¾ÛŒØ´â€ŒÙ\x81Ø±Ø¶ Ø§Ø´ØªØ±Ø§Ú©â€ŒÚ¯Ø°Ø§Ø±ÛŒ ÙˆØ¨Ù„Ø§Ú¯'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='listing_description',
            field=models.TextField(default='Ù…Ø\xadØªÙˆØ§ÛŒ Ú©Ø§Ø±Ø¨Ø±Ø¯ÛŒ Ø¨Ø±Ø§ÛŒ Ø§Ù†ØªØ®Ø§Ø¨ Ø®ÙˆØ¯Ø±Ùˆ Ùˆ Ø¯Ø±Ú© Ù\x81Ø±Ø§ÛŒÙ†Ø¯ ÙˆØ§Ø±Ø¯Ø§Øª Ùˆ ØªØ\xadÙˆÛŒÙ„.', verbose_name='ØªÙˆØ¶ÛŒØ\xad Ù\x81Ù‡Ø±Ø³Øª ÙˆØ¨Ù„Ø§Ú¯'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='listing_eyebrow',
            field=models.CharField(default='Ø±Ø§Ù‡Ù†Ù…Ø§ Ùˆ ØªØ¬Ø±Ø¨Ù‡', max_length=120, verbose_name='ØªÛŒØªØ± Ú©ÙˆØªØ§Ù‡ Ù\x81Ù‡Ø±Ø³Øª ÙˆØ¨Ù„Ø§Ú¯'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='listing_title',
            field=models.CharField(default='Ù…Ø¬Ù„Ù‡Ù” ÙˆØ§Ø±Ø¯Ø§Øª Ø®ÙˆØ¯Ø±Ùˆ', max_length=180, verbose_name='Ø¹Ù†ÙˆØ§Ù† Ù\x81Ù‡Ø±Ø³Øª ÙˆØ¨Ù„Ø§Ú¯'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='site_configuration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_configuration', to='core.siteconfiguration', verbose_name='ØªÙ†Ø¸ÛŒÙ…Ø§Øª Ø§ØµÙ„ÛŒ Ø³Ø§ÛŒØª'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Ù†Ø§Ù… Ø¯Ø³ØªÙ‡â€ŒØ¨Ù†Ø¯ÛŒ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='Ù†Ø§Ù…Ú©'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Ù†ÙˆÛŒØ³Ù†Ø¯Ù‡'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Ø¯Ø³ØªÙ‡â€ŒØ¨Ù†Ø¯ÛŒ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Ù…ØªÙ† Ù…Ø·Ù„Ø¨'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='ØªØµÙˆÛŒØ± Ú©Ø§ÙˆØ±'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image_alt',
            field=models.CharField(blank=True, max_length=180, verbose_name='Ù…ØªÙ† Ø¬Ø§ÛŒÚ¯Ø²ÛŒÙ† ØªØµÙˆÛŒØ± Ú©Ø§ÙˆØ±'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ø²Ù…Ø§Ù† Ø§ÛŒØ¬Ø§Ø¯'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='Ø®Ù„Ø§ØµÙ‡Ù” Ù…Ø·Ù„Ø¨'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='ØªÙˆØ¶ÛŒØ\xad Ø³Ø¦Ùˆ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ú©Ù„ÛŒØ¯ÙˆØ§Ú˜Ù‡â€ŒÙ‡Ø§ÛŒ Ø³Ø¦Ùˆ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/seo/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='ØªØµÙˆÛŒØ± Ø§Ø´ØªØ±Ø§Ú©â€ŒÚ¯Ø°Ø§Ø±ÛŒ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ø²Ù…Ø§Ù† Ø§Ù†ØªØ´Ø§Ø±'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Ø¹Ù†ÙˆØ§Ù† Ø³Ø¦Ùˆ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=240, unique=True, verbose_name='Ù†Ø§Ù…Ú©'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Ù¾ÛŒØ´â€ŒÙ†ÙˆÛŒØ³'), ('published', 'Ù…Ù†ØªØ´Ø±Ø´Ø¯Ù‡')], db_index=True, default='draft', max_length=10, verbose_name='ÙˆØ¶Ø¹ÛŒØª Ø§Ù†ØªØ´Ø§Ø±'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=220, verbose_name='Ø¹Ù†ÙˆØ§Ù†'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ø¢Ø®Ø±ÛŒÙ† ÙˆÛŒØ±Ø§ÛŒØ´'),
        ),
    ]
