# Generated by Django 5.0.6 on 2026-08-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_featured_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='فقط یک مقالهٔ منتشرشده به\u200cعنوان مقالهٔ ویژهٔ صفحهٔ مجله نمایش داده می\u200cشود.', verbose_name='مقالهٔ ویژهٔ مجله'),
        ),
    ]
