# Generated by Django 5.0.6 on 2026-08-13 12:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_is_featured'),
        ('core', '0005_add_blog_header_navigation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogconfiguration',
            options={'verbose_name': 'تنظیمات وبلاگ', 'verbose_name_plural': 'تنظیمات وبلاگ'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی وبلاگ', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای وبلاگ'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at', '-created_at'], 'permissions': [('publish_post', 'Can publish and unpublish blog posts')], 'verbose_name': 'مطلب وبلاگ', 'verbose_name_plural': 'مطالب وبلاگ'},
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='articles_per_page',
            field=models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(48)], verbose_name='تعداد مطلب در هر ØµÙ\x81حه'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='default_meta_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='توضیح پیش\u200cفرض سئوی وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='default_meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='کلیدواژه\u200cهای پیش\u200cفرض وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='default_meta_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='عنوان پیش\u200cفرض سئوی وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='default_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/seo/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='تصویر پیش\u200cفرض اشتراک\u200cگذاری وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='listing_description',
            field=models.TextField(default='محتوای کاربردی برای انتخاب خودرو و درک Ù\x81رایند واردات و تحویل.', verbose_name='توضیح Ù\x81هرست وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='listing_eyebrow',
            field=models.CharField(default='راهنما و تجربه', max_length=120, verbose_name='تیتر کوتاه Ù\x81هرست وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='listing_title',
            field=models.CharField(default='مجلهٔ واردات خودرو', max_length=180, verbose_name='عنوان Ù\x81هرست وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='site_configuration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_configuration', to='core.siteconfiguration', verbose_name='تنظیمات اصلی سایت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='نام دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='متن مطلب'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image_alt',
            field=models.CharField(blank=True, max_length=180, verbose_name='متن جایگزین تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='خلاصهٔ مطلب'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='توضیح سئو'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='کلیدواژه\u200cهای سئو'),
        ),
        migrations.AlterField(
            model_name='post',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/seo/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='تصویر اشتراک\u200cگذاری'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=240, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده')], db_index=True, default='draft', max_length=10, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=220, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
    ]
