# Generated by Django 5.0.6 on 2026-06-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('price_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('for_sale', 'For sale'), ('sold', 'Sold'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('target_delivery', models.DateField(blank=True, null=True)),
                ('channel_message_ids', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('telegram_file_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_cover', models.BooleanField(default=False)),
            ],
        ),
    ]
