# Generated by Django 5.0.6 on 2026-06-30 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('customers', '0001_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_at_stage', to='tracking.stage'),
        ),
        migrations.AddField(
            model_name='car',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='carphoto',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car'),
        ),
    ]
