# Generated by Django 5.0.6 on 2026-07-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('for_sale', 'For sale'), ('on_hold', 'On hold'), ('sold', 'Sold'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], default='draft', max_length=20),
        ),
    ]
