# Generated by Django 5.0.6 on 2026-07-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_vehiclehold_vehiclehold_one_active_hold_per_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
