# Generated by Django 5.0.6 on 2026-07-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_tracking_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at'], 'permissions': [('publish_vehicle', 'Can publish a vehicle for sale'), ('hold_vehicle', 'Can place a vehicle on hold'), ('release_vehicle_hold', 'Can release a vehicle hold'), ('sell_vehicle', 'Can mark a vehicle as sold'), ('archive_vehicle', 'Can archive a vehicle')]},
        ),
    ]
