# Generated by Django 5.0.6 on 2026-07-29 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleArchiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('archived', 'Archived'), ('restored', 'Restored')], max_length=20)),
                ('previous_status', models.CharField(choices=[('draft', 'Draft'), ('for_sale', 'For sale'), ('on_hold', 'On hold'), ('sold', 'Sold'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'Draft'), ('for_sale', 'For sale'), ('on_hold', 'On hold'), ('sold', 'Sold'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], max_length=20)),
                ('source', models.CharField(choices=[('system', 'System'), ('admin_dashboard', 'Admin dashboard'), ('website', 'Website'), ('telegram_bot', 'Telegram bot')], default='system', max_length=30)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archive_events', to='cars.car')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_archive_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['car', 'created_at'], name='vehicle_archive_car_time_idx')],
            },
        ),
    ]
