# Generated by Django 5.0.6 on 2026-08-01

from django.db import migrations, models
from django.utils.text import slugify


def populate_car_slugs(apps, schema_editor):
    Car = apps.get_model("cars", "Car")
    existing_slugs = set(
        Car.objects.exclude(slug__isnull=True)
        .exclude(slug="")
        .values_list("slug", flat=True)
    )

    for car in Car.objects.filter(slug__isnull=True).order_by("pk"):
        base_slug = slugify(car.title, allow_unicode=True).strip("-") or f"vehicle-{car.pk}"
        base_slug = base_slug[:220]
        candidate = base_slug
        suffix_number = 2

        while candidate in existing_slugs:
            suffix = f"-{suffix_number}"
            candidate = f"{base_slug[: 240 - len(suffix)]}{suffix}"
            suffix_number += 1

        car.slug = candidate
        car.save(update_fields=["slug"])
        existing_slugs.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_vehiclearchiveevent"),
        ("customers", "0003_alter_customvehiclerequest_options"),
        ("tracking", "0010_alter_trackingevent_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carphoto",
            options={"ordering": ["-is_cover", "sort_order", "pk"]},
        ),
        migrations.AddField(
            model_name="car",
            name="seo_description",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="car",
            name="seo_keywords",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="car",
            name="seo_title",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="car",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=240,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="carphoto",
            name="alt_text",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="carphoto",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["status", "is_deleted", "is_featured"],
                name="public_car_visibility_idx",
            ),
        ),
        migrations.RunPython(populate_car_slugs, migrations.RunPython.noop),
    ]
