# Generated by Django 5.0.6 on 2026-08-02

import cars.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_alter_carphoto_options_car_seo_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="spin_360_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CarSpinFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="image_height",
                        upload_to=cars.models.car_spin_frame_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                        width_field="image_width",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "image_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "image_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spin_frames",
                        to="cars.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "فریم نمای ۳۶۰ خودرو",
                "verbose_name_plural": "فریم‌های نمای ۳۶۰ خودرو",
                "ordering": ["sequence", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="carspinframe",
            constraint=models.UniqueConstraint(
                fields=("car", "sequence"),
                name="car_spin_frame_unique_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="carspinframe",
            constraint=models.CheckConstraint(
                check=models.Q(("sequence__gte", 1)),
                name="car_spin_frame_sequence_gte_1",
            ),
        ),
    ]
