# Generated by Django 5.0.6 on 2026-08-04 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_spin_360_enabled_carspinframe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInventoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], max_length=20)),
                ('source', models.CharField(choices=[('backoffice', 'Backoffice'), ('telegram_bot', 'Telegram bot'), ('django_admin', 'Django admin')], default='backoffice', max_length=30)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_events', to='cars.car')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_inventory_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رویداد موجودی ماشین',
                'verbose_name_plural': 'رویدادهای موجودی ماشین',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['car', 'created_at'], name='vehicle_inv_event_time_idx')],
            },
        ),
    ]
