# Generated by Django 5.0.6 on 2026-08-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_carvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at'], 'permissions': [('publish_vehicle', 'Can publish a vehicle for sale'), ('hold_vehicle', 'Can place a vehicle on hold'), ('release_vehicle_hold', 'Can release a vehicle hold'), ('sell_vehicle', 'Can mark a vehicle as sold'), ('archive_vehicle', 'Can archive a vehicle'), ('reverse_vehicle_sale', 'Can reverse a sale during the first tracking stage')]},
        ),
        migrations.AlterField(
            model_name='vehicleinventoryevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('sale_reversed', 'Sale reversed')], max_length=20),
        ),
    ]
