# Generated by Django 5.0.6 on 2026-07-28 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_tracking_code'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVehicleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('telegram_id', models.CharField(blank=True, max_length=50)),
                ('desired_vehicle_description', models.TextField(help_text='توضیح آزاد مشتری دربارهٔ خودروی موردنظر')),
                ('preferred_brand', models.CharField(blank=True, max_length=100)),
                ('preferred_model', models.CharField(blank=True, max_length=100)),
                ('preferred_year_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('preferred_year_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('preferred_color', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('website', 'وب\u200cسایت'), ('telegram_bot', 'ربات تلگرام')], default='website', max_length=20)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('sold', 'فروخته\u200cشده')], default='new', max_length=10)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sold_custom_vehicle_requests', to=settings.AUTH_USER_MODEL)),
                ('sold_car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_vehicle_request', to='cars.car')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomVehicleRequestReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_vehicle_request_read_receipts', to=settings.AUTH_USER_MODEL)),
                ('vehicle_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='customers.customvehiclerequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customvehiclerequest',
            constraint=models.CheckConstraint(check=models.Q(('preferred_year_from__isnull', True), ('preferred_year_to__isnull', True), ('preferred_year_from__lte', models.F('preferred_year_to')), _connector='OR'), name='custom_vehicle_request_valid_year_range'),
        ),
        migrations.AddConstraint(
            model_name='customvehiclerequest',
            constraint=models.CheckConstraint(check=models.Q(('budget_amount__gt', 0)), name='custom_vehicle_request_positive_budget'),
        ),
        migrations.AddConstraint(
            model_name='customvehiclerequest',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('sold_at__isnull', True), ('sold_by__isnull', True), ('sold_car__isnull', True), ('status', 'new')), models.Q(('sold_at__isnull', False), ('sold_by__isnull', False), ('sold_car__isnull', False), ('status', 'sold')), _connector='OR'), name='custom_vehicle_request_consistent_sale_state'),
        ),
        migrations.AddConstraint(
            model_name='customvehiclerequestreadreceipt',
            constraint=models.UniqueConstraint(fields=('vehicle_request', 'employee'), name='one_read_receipt_per_employee_and_request'),
        ),
    ]
