# Generated by Django 5.0.6 on 2026-07-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customvehiclerequest_customvehiclerequestreadreceipt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customvehiclerequest',
            options={'ordering': ['-created_at'], 'permissions': [('convert_custom_vehicle_request_to_sale', 'Can convert a custom vehicle request to sale')]},
        ),
    ]
