# Generated by Django 5.0.6 on 2026-07-30 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0007_vehiclearchiveevent'),
        ('tracking', '0010_alter_trackingevent_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramInboundUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_update_id', models.BigIntegerField(unique=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('update_type', models.CharField(choices=[('message', 'Message'), ('callback_query', 'Callback query'), ('unsupported', 'Unsupported')], max_length=30)),
                ('command_name', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error_summary', models.CharField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramStaffLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('telegram_chat_id', models.BigIntegerField()),
                ('telegram_username', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('unlink_reason', models.TextField(blank=True)),
                ('unlinked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_telegram_staff_links', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_staff_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-linked_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramOutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('send_message', 'Send message'), ('answer_callback', 'Answer callback')], default='send_message', max_length=30)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('callback_query_id', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('reply_markup', models.JSONField(blank=True, null=True)),
                ('reply_to_message_id', models.BigIntegerField(blank=True, null=True)),
                ('message_type', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('retry', 'Retry'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('last_error_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbound_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbox_messages', to='integrations.telegraminboundupdate')),
                ('staff_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbox_messages', to='integrations.telegramstafflink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='telegraminboundupdate',
            name='staff_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_updates', to='integrations.telegramstafflink'),
        ),
        migrations.CreateModel(
            name='TelegramStaffLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_telegram_link_tokens', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_telegram_link_tokens', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_link_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramStageConfirmationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_confirmation_sessions', to='cars.car')),
                ('staff_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmation_sessions', to='integrations.telegramstafflink')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_confirmation_sessions', to='tracking.stage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='telegramstafflink',
            index=models.Index(fields=['telegram_user_id', 'is_active'], name='telegram_staff_user_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='telegramstafflink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='one_active_telegram_link_per_staff_user'),
        ),
        migrations.AddConstraint(
            model_name='telegramstafflink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('telegram_user_id',), name='one_active_staff_link_per_telegram_user'),
        ),
        migrations.AddConstraint(
            model_name='telegramstafflink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('telegram_chat_id',), name='one_active_staff_link_per_telegram_chat'),
        ),
        migrations.AddIndex(
            model_name='telegramoutboxmessage',
            index=models.Index(fields=['status', 'next_attempt_at'], name='telegram_outbox_state_next_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramoutboxmessage',
            index=models.Index(fields=['chat_id', 'created_at'], name='telegram_outbox_chat_time_idx'),
        ),
        migrations.AddIndex(
            model_name='telegraminboundupdate',
            index=models.Index(fields=['telegram_user_id', 'received_at'], name='telegram_update_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='telegraminboundupdate',
            index=models.Index(fields=['status', 'received_at'], name='tg_update_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramstafflinktoken',
            index=models.Index(fields=['user', 'expires_at'], name='telegram_token_user_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramstageconfirmationsession',
            index=models.Index(fields=['staff_link', 'status', 'expires_at'], name='tg_session_staff_state_idx'),
        ),
    ]
