# Generated by Django 5.0.6 on 2026-07-30 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_vehiclearchiveevent'),
        ('customers', '0003_alter_customvehiclerequest_options'),
        ('integrations', '0001_initial'),
        ('tracking', '0010_alter_trackingevent_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTelegramSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('telegram_chat_id', models.BigIntegerField()),
                ('telegram_username', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_reason', models.CharField(blank=True, max_length=255)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_customer_subscriptions', to='cars.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_tracking_subscriptions', to='customers.customer')),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddField(
            model_name='telegraminboundupdate',
            name='customer_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_updates', to='integrations.customertelegramsubscription'),
        ),
        migrations.AddField(
            model_name='telegramoutboxmessage',
            name='customer_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbox_messages', to='integrations.customertelegramsubscription'),
        ),
        migrations.CreateModel(
            name='CustomerTrackingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbox_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_tracking_notification', to='integrations.telegramoutboxmessage')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_notifications', to='integrations.customertelegramsubscription')),
                ('tracking_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_notifications', to='tracking.trackingevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramCustomerActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_customer_activation_tokens', to='cars.car')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customer_telegram_activation_tokens', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_activation_tokens', to='customers.customer')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_customer_telegram_activation_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('issue_customer_telegram_activation', 'Can issue a customer Telegram activation code')],
            },
        ),
        migrations.AddIndex(
            model_name='customertelegramsubscription',
            index=models.Index(fields=['telegram_user_id', 'is_active'], name='tg_customer_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customertelegramsubscription',
            index=models.Index(fields=['telegram_chat_id', 'is_active'], name='tg_customer_chat_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='customertelegramsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('car',), name='one_active_customer_subscription_per_car'),
        ),
        migrations.AddIndex(
            model_name='customertrackingnotification',
            index=models.Index(fields=['subscription', 'created_at'], name='tg_cust_notice_sub_idx'),
        ),
        migrations.AddConstraint(
            model_name='customertrackingnotification',
            constraint=models.UniqueConstraint(fields=('tracking_event', 'subscription'), name='one_customer_notification_per_tracking_event'),
        ),
        migrations.AddIndex(
            model_name='telegramcustomeractivationtoken',
            index=models.Index(fields=['car', 'expires_at'], name='tg_cust_token_car_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramcustomeractivationtoken',
            index=models.Index(fields=['customer', 'expires_at'], name='tg_cust_token_user_exp_idx'),
        ),
    ]
