# Generated by Django 5.0.6 on 2026-08-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_telegram_outbox_vehicle_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramoutboxmessage',
            name='media_object_refs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramvehiclepublication',
            name='content_mode',
            field=models.CharField(default='message', max_length=20),
        ),
        migrations.AlterField(
            model_name='telegramoutboxmessage',
            name='operation',
            field=models.CharField(choices=[('send_message', 'Send message'), ('edit_message', 'Edit message'), ('send_photo', 'Send photo'), ('send_video', 'Send video'), ('send_media_group', 'Send media group'), ('edit_media_caption', 'Edit media caption'), ('answer_callback', 'Answer callback')], default='send_message', max_length=30),
        ),
    ]
