# Generated by Django 5.0.6 on 2026-08-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_telegramoutboxmessage_media_object_refs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramoutboxmessage',
            name='operation',
            field=models.CharField(choices=[('send_message', 'Send message'), ('edit_message', 'Edit message'), ('send_photo', 'Send photo'), ('send_video', 'Send video'), ('send_media_group', 'Send media group'), ('edit_media_caption', 'Edit media caption'), ('delete_message', 'Delete message'), ('answer_callback', 'Answer callback')], default='send_message', max_length=30),
        ),
    ]
