# Generated by Django 5.0.6 on 2026-07-22 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_duration_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transitions', to='tracking.stage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='tracking.stage')),
            ],
            options={
                'ordering': ['from_stage__order', 'to_stage__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='stagetransition',
            constraint=models.UniqueConstraint(fields=('from_stage', 'to_stage'), name='unique_stage_transition'),
        ),
        migrations.AddConstraint(
            model_name='stagetransition',
            constraint=models.CheckConstraint(check=models.Q(('from_stage', models.F('to_stage')), _negated=True), name='stage_transition_cannot_point_to_itself'),
        ),
    ]
