# Generated by Django 5.0.6 on 2026-07-23 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_tracking_code'),
        ('tracking', '0002_stagetransition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tracking_started', 'Tracking started'), ('stage_confirmed', 'Stage confirmed'), ('stage_corrected', 'Stage corrected'), ('stage_skipped', 'Stage skipped')], max_length=30)),
                ('source', models.CharField(choices=[('system', 'System'), ('admin_dashboard', 'Admin dashboard'), ('telegram_bot', 'Telegram bot'), ('excel_import', 'Excel import')], default='system', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_events', to='cars.car')),
                ('new_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracking_events_to', to='tracking.stage')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracking_events', to=settings.AUTH_USER_MODEL)),
                ('previous_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracking_events_from', to='tracking.stage')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['car', 'created_at'], name='tracking_event_car_time_idx')],
            },
        ),
    ]
