# Generated by Django 5.0.6 on 2026-07-27 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_tracking_code'),
        ('tracking', '0003_trackingevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carstageprogress',
            name='skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carstageprogress',
            name='skipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skipped_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='carstageprogress',
            constraint=models.CheckConstraint(check=models.Q(('actual_arrival__isnull', True), ('skipped_at__isnull', True), _connector='OR'), name='progress_cannot_be_confirmed_and_skipped'),
        ),
    ]
