# Generated by Django 5.0.6 on 2026-07-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_carstageprogress_skipped_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingevent',
            options={'ordering': ['created_at'], 'permissions': [('skip_tracking_stage', 'Can skip a tracking stage'), ('correct_tracking_stage', 'Can correct tracking stages')]},
        ),
    ]
