# Generated by Django 5.0.6 on 2026-07-27 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_tracking_code'),
        ('tracking', '0005_alter_trackingevent_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carstageprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carstageprogress',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='carstageprogress',
            constraint=models.CheckConstraint(check=models.Q(('completed_at__isnull', True), ('actual_arrival__isnull', False), _connector='OR'), name='progress_cannot_complete_before_entry'),
        ),
    ]
