# Generated by Django 5.0.6 on 2026-07-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_carstageprogress_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='event_type',
            field=models.CharField(choices=[('tracking_started', 'Tracking started'), ('stage_confirmed', 'Stage entered'), ('stage_completed', 'Stage completed'), ('stage_corrected', 'Stage corrected'), ('stage_skipped', 'Stage skipped')], max_length=30),
        ),
    ]
