# Generated by Django 5.0.6 on 2026-07-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_trackingevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='event_type',
            field=models.CharField(choices=[('tracking_started', 'Tracking started'), ('stage_confirmed', 'Stage entered'), ('stage_completed', 'Stage completed'), ('stage_corrected', 'Stage corrected'), ('stage_skipped', 'Stage skipped'), ('stage_archived', 'Stage archived')], max_length=30),
        ),
    ]
