# Generated by Django 5.0.6 on 2026-07-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_alter_trackingevent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingevent',
            options={'ordering': ['created_at'], 'permissions': [('confirm_tracking_stage', 'Can confirm an assigned tracking stage'), ('import_tracking_stage_updates', 'Can import tracking stage updates'), ('skip_tracking_stage', 'Can skip a tracking stage'), ('correct_tracking_stage', 'Can correct tracking stages'), ('archive_tracking_stage', 'Can archive a tracking stage')]},
        ),
    ]
